name: customer1-development
description: Development environment for Customer1

variables:
  APP_ENV: development
  LOG_LEVEL: debug
  CUSTOMER: customer1

mariadb:
  version: "10.11"
  port: 3306
  bind_address: "0.0.0.0"
  max_connections: 151
  character_set_server: "utf8mb4"
  collation_server: "utf8mb4_general_ci"

playbooks:
  basic_setup:
    name: Basic System Setup
    description: Install common tools and packages
    hosts: ["*"]  # Run on all hosts
    include_roles:
      - common

  database_setup:
    name: Database Server Setup
    description: Install and configure MariaDB database server
    hosts: ["dev-db-*"]  # Will match dev-db-01.customer1.local, etc.
    include_roles:
      - mariadb
