---
name: Debug Playbook
description: Test if playbook execution works
customer: customer1
environment: production

# Include common tasks first
include: /etc/for/environments/roles/common/tasks.yml

# Customer-specific tasks
tasks:
  - name: Debug - Echo Test
    command: echo "Debug test executed at $(date)"
    when: "*"

  - name: Debug - Write Test File
    command: |
      echo "Test executed at $(date)" > /tmp/for-debug.txt
    when: "*"

  - name: Configure customer-specific settings
    command: |
      echo "CUSTOMER_NAME=customer1" > /etc/customer-config
      echo "ENVIRONMENT=production" >> /etc/customer-config
    when: "*"

  - name: Install customer-specific packages
    command: apt-get install -y postgresql-client redis-tools
    when: "*"
