version: 2

project_name: for-IT

before:
  hooks:
    - go mod tidy

builds:
  - id: for-server
    main: ./cmd/server
    binary: for-server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

  - id: for-client
    main: ./cmd/client
    binary: for-client
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - id: for-archive
    name_template: "for-IT_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    files:
      - README.md
      - LICENSE
      - systemd/*
      - scripts/*

nfpms:
  - id: for-server-package
    package_name: for-server
    file_name_template: "for-server_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - for-server
    vendor: DiceOne
    homepage: https://github.com/diceone/for-IT
    maintainer: DiceOne <your.email@example.com>
    description: For Automation Framework Server
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/local/bin
    contents:
      - src: systemd/for-server.service
        dst: /etc/systemd/system/for-server.service
        type: config
    scripts:
      preinstall: "scripts/preinstall.sh"
      postinstall: "scripts/postinstall.sh"
    rpm:
      group: Applications/System

  - id: for-client-package
    package_name: for-client
    file_name_template: "for-client_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - for-client
    vendor: DiceOne
    homepage: https://github.com/diceone/for-IT
    maintainer: DiceOne <your.email@example.com>
    description: For Automation Framework Client
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/local/bin
    contents:
      - src: systemd/for-client.service
        dst: /etc/systemd/system/for-client.service
        type: config
    scripts:
      preinstall: "scripts/preinstall.sh"
      postinstall: "scripts/postinstall.sh"
    rpm:
      group: Applications/System

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: diceone
    name: for-IT
  draft: true
  prerelease: auto
  mode: replace
