---
# Common tasks that can be used across all customers
tasks:
  - name: Update package cache
    command: apt-get update
    when: "{{ .Hostname }}"

  - name: Install common packages
    command: apt-get install -y curl wget htop
    when: "{{ .Hostname }}"

  - name: Configure system limits
    command: |
      sysctl -w fs.file-max=65535
      sysctl -w net.ipv4.tcp_max_syn_backlog=4096
    when: "{{ .Hostname }}"
