name: Common Tools and Packages
description: Install basic common tools and packages needed on all systems
tasks:
  - name: Install vim package
    command: |
      if command -v apt-get >/dev/null 2>&1; then
        apt-get install -y vim
      elif command -v dnf >/dev/null 2>&1; then
        dnf install -y vim
      elif command -v yum >/dev/null 2>&1; then
        yum install -y vim
      elif command -v pacman >/dev/null 2>&1; then
        pacman -S --noconfirm vim
      else
        echo "Unsupported package manager"
        exit 1
      fi
    when: "*"  # Run on all hosts
